const allCities = [
    "New York", "London", "Paris", "Tokyo", "Beijing", "Mumbai", "Karachi", "Lahore", "Delhi", "Cairo",
    "Moscow", "Istanbul", "Bangkok", "Dubai", "Los Angeles", "Chicago", "Houston", "Toronto", "Vancouver",
    "Mexico City", "São Paulo", "Rio de Janeiro", "Buenos Aires", "Lima", "Bogotá", "Santiago", "Madrid",
    "Barcelona", "Rome", "Berlin", "Munich", "Vienna", "Amsterdam", "Brussels", "Lisbon", "Zurich",
    "Stockholm", "Copenhagen", "Oslo", "Helsinki", "Warsaw", "Prague", "Budapest", "Athens", "Belgrade",
    "Bucharest", "Sofia", "Ankara", "Tehran", "Baghdad", "Kuwait City", "Doha", "Riyadh", "Jeddah", "Medina",
    "Mecca", "Amman", "Damascus", "Beirut", "Jerusalem", "Cape Town", "Johannesburg", "Nairobi", "Accra",
    "Lagos", "Abuja", "Addis Ababa", "Casablanca", "Algiers", "Tunis", "Tripoli", "Khartoum", "Kigali",
    "Harare", "Gaborone", "Windhoek", "Canberra", "Sydney", "Melbourne", "Brisbane", "Perth", "Auckland",
    "Wellington", "Suva", "Port Moresby", "Honolulu", "Anchorage", "San Francisco", "Seattle", "Boston",
    "Philadelphia", "Phoenix", "Dallas", "San Diego", "Miami", "Atlanta", "Washington", "Detroit",
    "Minneapolis", "Denver", "Las Vegas", "Portland", "Tampa", "Orlando", "San Antonio", "Charlotte",
    "Indianapolis", "Cleveland", "Pittsburgh", "Cincinnati", "St. Louis", "Kansas City", "Columbus",
    "Milwaukee", "Omaha", "Salt Lake City", "Buffalo", "Rochester", "Albany", "Montreal", "Ottawa",
    "Calgary", "Edmonton", "Winnipeg", "Quebec City", "Halifax", "St. John's", "Victoria", "Regina",
    "Saskatoon", "Yellowknife", "Whitehorse", "Iqaluit", "Guadalajara", "Monterrey",
    "Tijuana", "Puebla", "Leon", "Juarez", "Hermosillo", "Cancun", "Merida", "Havana", "Santo Domingo",
    "Port-au-Prince", "Kingston", "San Juan", "Panama City", "San Jose", "Managua", "Tegucigalpa",
    "Guatemala City", "Belize City", "San Salvador", "Caracas", "Quito", "La Paz", "Asuncion", "Montevideo",
    "Georgetown", "Paramaribo", "Cayenne", "Reykjavik", "Tallinn", "Riga", "Vilnius", "Chisinau", "Tbilisi",
    "Yerevan", "Baku", "Astana", "Tashkent", "Bishkek", "Dushanbe", "Ulaanbaatar", "Seoul", "Busan", "Incheon",
    "Pyongyang", "Hanoi", "Ho Chi Minh City", "Phnom Penh", "Vientiane", "Yangon", "Naypyidaw", "Jakarta",
    "Bandung", "Surabaya", "Denpasar", "Kuala Lumpur", "George Town", "Singapore", "Bangkok", "Chiang Mai",
    "Manila", "Cebu City", "Davao City", "Taipei", "Kaohsiung", "Hong Kong", "Macau", "Shenzhen", "Guangzhou",
    "Chengdu", "Wuhan", "Xi'an", "Hangzhou", "Nanjing", "Tianjin", "Shenyang", "Harbin", "Urumqi", "Lhasa",
    "Seville", "Valencia", "Granada", "Malaga", "Bilbao", "Zaragoza", "Palermo", "Naples", "Florence",
    "Venice", "Genoa", "Turin", "Nice", "Lyon", "Marseille", "Bordeaux", "Toulouse", "Lille", "Nantes",
    "Strasbourg", "Frankfurt", "Hamburg", "Cologne", "Dusseldorf", "Leipzig", "Stuttgart", "Dresden",
    "Bremen", "Hannover", "Krakow", "Gdansk", "Poznan", "Wroclaw", "Katowice", "Lublin", "Abilene", "Aden", "Agra", "Ajmer", "Akron", "Albany", "Aligarh", "Allentown", "Amarillo", "Amritsar",
    "Andorra la Vella", "Ann Arbor", "Antalya", "Antananarivo", "Arkhangelsk", "Arusha", "Ashgabat", "Aswan", "Asyut", "Atyrau",
    "Aurangabad", "Aurora", "Bacolod", "Bakersfield", "Balikpapan", "Bamako", "Banda Aceh", "Bandar Abbas", "Bandar Seri Begawan", "Banjul",
    "Bari", "Baton Rouge", "Batumi", "Bayamo", "Beira", "Bellingham", "Bend", "Benghazi", "Benin City", "Bentonville",
    "Bergen", "Berhampur", "Bhatinda", "Bhavnagar", "Bhiwandi", "Bhimavaram", "Bhopal", "Bikaner", "Bilaspur", "Bismarck",
    "Bloemfontein", "Boise", "Bordeaux", "Bossier City", "Bradford", "Bratislava", "Brazzaville", "Brest", "Brindisi", "Bristol",
    "Broken Arrow", "Bruges", "Bujumbura", "Bulawayo", "Bursa", "Bushehr", "Bydgoszcz", "Cabanatuan", "Cagayan de Oro", "Calamba",
    "Cambridge", "Campo Grande", "Can Tho", "Canberra", "Cape Coast", "Caracas", "Cartagena", "Catania", "Cauayan", "Cavite City",
    "Cedar Rapids", "Chandrapur", "Changwon", "Charlotte Amalie", "Cheboksary", "Chelyabinsk", "Chengde", "Cherepovets", "Chernivtsi", "Chesapeake",
    "Chiba", "Chiclayo", "Chihuahua", "Chittagong", "Cholula", "Christchurch", "Ciudad Bolivar", "Ciudad Guayana", "Cluj-Napoca", "Cochabamba",
    "Coimbatore", "Colón", "Colombo", "Conakry", "Concord", "Constanța", "Cotonou", "Cuernavaca", "Culiacán", "Curitiba",
    "Da Nang", "Daegu", "Dakar", "Damanhur", "Dammam", "Davao", "Dearborn", "Debrecen", "Denizli", "Des Moines",
    "Dezful", "Dijon", "Dili", "Djibouti", "Dnipro", "Dodoma", "Donetsk", "Dresden", "Duqm", "Durango",
    "Dushanbe", "East London", "El Alto", "El Paso", "Elblag", "Enugu", "Erbil", "Erzurum", "Eskişehir", "Eswatini",
    "Eugene", "Evansville", "Faisalabad", "Faridabad", "Fergana", "Fez", "Flagstaff", "Florence", "Fort Wayne", "Fresno",
    "Fukui", "Fukuoka", "Funchal", "Gaborone", "Gainesville", "Galway", "Gandhinagar", "Ganja", "Gdynia", "Gelsenkirchen",
    "Genk", "Genoa", "Ghaziabad", "Gijón", "Giza", "Goa", "Goma", "Gondar", "Gorakhpur", "Gothenburg",
    "Greensboro", "Grozny", "Guntur", "Guwahati", "Gwangju", "Gyumri", "Haifa", "Haikou", "Hakodate", "Halifax",
    "Hamilton", "Hamhung", "Hargeisa", "Harrisburg", "Hartford", "Havana", "Hawalli", "Hebron", "Hermosillo", "Hilo",
    "Hobart", "Hoover", "Hsinchu", "Hualien", "Hubli", "Huntsville", "Hwasung", "Ibadan", "Ibaraki", "Ibb",
    "Ichikawa", "Ifrane", "Iligan", "Imphal", "Ingolstadt", "Ipoh", "Irbid", "Irkutsk", "Isfahan", "Itanagar",
    "Iwaki", "Izmir", "Jabalpur", "Jaboatao", "Jacmel", "Jaen", "Jaffna", "Jagdalpur", "Jalandhar", "Jambi",
    "Jamestown", "Jamshedpur", "Jinan", "Jinja", "Joao Pessoa", "Jodhpur", "Jos", "Juarez", "Juba", "Jujuy",
    "Juneau", "Jyvaskyla", "Kabul", "Kaduna", "Kagoshima", "Kaifeng", "Kairouan", "Kajaani", "Kakinada", "Kaliningrad"
];
